import { liveTools, type ToolDefinition } from '@config/tools'
import Link from 'next/link'
import { toolContent } from '@/lib/seo/toolContent'

/**
 * The copy below a tool page's toolkit: intro, FAQ, and links to related tools.
 *
 * Server-rendered so it is in the HTML search engines receive, and so it costs the
 * visitor no JavaScript.
 */
export function ToolPageContent({ tool }: { tool: ToolDefinition }) {
  const content = toolContent(tool)
  const related = relatedTools(tool)

  return (
    <div className="mt-12 flex flex-col gap-10 border-border border-t pt-10">
      <section>
        <h2 className="font-medium text-fg-primary text-lg">Common questions</h2>
        <dl className="mt-4 flex flex-col gap-5">
          {content.faq.map((entry) => (
            <div key={entry.question}>
              <dt className="font-medium text-fg-primary text-sm">{entry.question}</dt>
              <dd className="mt-1 text-fg-secondary text-sm leading-relaxed">{entry.answer}</dd>
            </div>
          ))}
        </dl>
      </section>

      {related.length > 0 ? (
        <section>
          <h2 className="font-medium text-fg-primary text-lg">Related tools</h2>
          <ul className="mt-3 flex flex-wrap gap-2">
            {related.map((entry) => (
              <li key={entry.slug}>
                <Link
                  href={`/${entry.slug}`}
                  className="inline-block rounded-[--radius-sm] border border-border bg-bg-raised px-3 py-1.5 text-fg-secondary text-sm transition-colors hover:border-brand hover:text-fg-primary"
                >
                  {entry.title}
                </Link>
              </li>
            ))}
          </ul>
          <p className="mt-4 text-fg-muted text-sm">
            Or use{' '}
            <Link href="/" className="text-brand underline underline-offset-2">
              the full builder
            </Link>{' '}
            to combine any of these in a single pass.
          </p>
        </section>
      ) : null}
    </div>
  )
}

/**
 * Picks sibling tools worth linking to, preferring ones sharing a format with this
 * page so the links are genuinely relevant rather than a link farm.
 */
function relatedTools(tool: ToolDefinition): readonly ToolDefinition[] {
  const others = liveTools().filter((candidate) => candidate.slug !== tool.slug)

  const sharesFormat = others.filter(
    (candidate) =>
      tool.conversion &&
      candidate.conversion &&
      (candidate.conversion.from === tool.conversion.from ||
        candidate.conversion.to === tool.conversion.to),
  )

  const standalone = others.filter((candidate) => !candidate.conversion)

  // De-duplicate while preserving the ordering above, then cap the list: a page
  // that links everywhere passes no signal about what is actually related.
  return [...new Set([...sharesFormat, ...standalone])].slice(0, 6)
}

/**
 * FAQPage structured data.
 *
 * Mirrors exactly what is rendered above. Structured data that does not match the
 * visible page is a manual-action risk, so both come from the same source.
 */
export function ToolStructuredData({ tool }: { tool: ToolDefinition }) {
  const content = toolContent(tool)

  const schema = {
    '@context': 'https://schema.org',
    '@type': 'FAQPage',
    mainEntity: content.faq.map((entry) => ({
      '@type': 'Question',
      name: entry.question,
      acceptedAnswer: { '@type': 'Answer', text: entry.answer },
    })),
  }

  return (
    <script
      type="application/ld+json"
      // biome-ignore lint/security/noDangerouslySetInnerHtml: JSON-LD generated by JSON.stringify from typed config; never user input, and a script tag has no other way to carry it
      dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }}
    />
  )
}
