/**
 * Generates `out/_headers` from config/security.ts — P5-02.
 *
 * `headers()` in next.config.ts does not run in a static export; Next says so at
 * build time. On Cloudflare the equivalent is a `_headers` file at the root of the
 * output directory. Writing that by hand would give the CSP two sources of truth and
 * let the served policy drift from the reviewed one, so it is generated from the same
 * module the dev server uses.
 *
 * It also refuses to emit COOP or COEP. Those headers enable cross-origin isolation,
 * which silently kills AdSense and is the reason this project uses jSquash rather
 * than wasm-vips (ADR-0002). config/security.ts says never to add them; this makes
 * that unenforceable-by-comment rule fail the build instead.
 *
 * Runs after `next build`, which regenerates `out/`.
 */

import { writeFileSync } from 'node:fs'
import { registerHooks } from 'node:module'
import { join } from 'node:path'

// The config modules import each other without file extensions, which Next resolves
// and bare Node ESM does not. Retrying with `.ts` is the whole adaptation needed to
// read the real config rather than a copy of it.
registerHooks({
  resolve(specifier, context, nextResolve) {
    try {
      return nextResolve(specifier, context)
    } catch {
      return nextResolve(`${specifier}.ts`, context)
    }
  },
})

const { securityHeaders } = await import('../config/security.ts')

/** Cross-origin isolation. Never emitted. See ADR-0002 and the security skill. */
const FORBIDDEN = ['cross-origin-embedder-policy', 'cross-origin-opener-policy']

const offending = securityHeaders.filter((header) => FORBIDDEN.includes(header.key.toLowerCase()))

if (offending.length > 0) {
  console.error(
    `config/security.ts sets ${offending.map((h) => h.key).join(' and ')}.\n` +
      'Cross-origin isolation removes all ad revenue and breaks Stripe, YouTube and\n' +
      'Google Sign-In. If a library needs SharedArrayBuffer, the answer is a different\n' +
      'library. See docs/adr/0002-jsquash-over-wasm-vips.md.',
  )
  process.exit(1)
}

/**
 * Cloudflare's format: a path pattern, then indented `Name: value` lines. `/*`
 * matches every route, which is what next.config.ts applies today.
 */
function render(headers) {
  const lines = [
    '# Generated by scripts/headers.mjs from config/security.ts.',
    '# Do not edit.',
    '',
    '/*',
  ]
  for (const header of headers) {
    lines.push(`  ${header.key}: ${header.value}`)
  }
  return `${lines.join('\n')}\n`
}

const outDir = process.argv[2] ?? 'out'
const target = join(outDir, '_headers')

writeFileSync(target, render(securityHeaders))
console.log(`wrote ${target} — ${securityHeaders.length} headers`)
